// Serves the service worker at /sw.js as a BUILD-STAMPED static route (the
// previous public/sw.js never changed bytes between deploys, so browsers never
// reinstalled it and the precached /offline shell went stale — its hashed
// chunks 404 after later deploys; see the resolved BACKLOG [debt]).
// force-static + no request access → prerendered at build; the interpolated
// build id byte-diffs the worker every deploy → reinstall → fresh precache,
// and the activate sweep below deletes the previous cache generation.
// pwa-provider.tsx keeps registering "/sw.js" — same URL, root scope.
// The worker source is embedded as a template literal (kept dependency-free
// and lint-clean; worker globals never leak into the TS module).
export const dynamic = "force-static";

const buildId = process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 8) ?? Date.now().toString(36);

const worker = /* js */ `// Ignaite service worker — hand-rolled, dependency-free, build-stamped (the
// cache name embeds the deploy's build id; generated by app/sw.js/route.ts).
// Its job is twofold:
//   1. Satisfy Chrome's installability criteria (a SW with a fetch handler) so
//      our custom install prompt fires reliably instead of the flaky native one.
//   2. Provide an offline app shell + a branded /offline fallback.
//
// Caching strategy (kept intentionally small):
//   • navigations  → network-first, fall back to cached page, then /offline
//   • static assets→ stale-while-revalidate (instant, refreshed in background)
//   • everything else (cross-origin, analytics, POST/server actions) → passthrough
const CACHE = "ignaite-shell-${buildId}";

// App shell precached on install. Keep this lean — just the entry route, the
// offline fallback, and the manifest. Hashed /_next/static assets are picked up
// lazily by the stale-while-revalidate path below.
const PRECACHE_URLS = ["/", "/offline", "/manifest.webmanifest"];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // addAll is atomic; if one URL 404s the whole install fails, so keep the
      // list to routes we know resolve. Guard each add instead of a strict
      // addAll so a single failure doesn't brick the SW.
      .then((cache) =>
        Promise.allSettled(PRECACHE_URLS.map((url) => cache.add(url))),
      )
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

// Static assets we serve stale-while-revalidate: Next build output, our dynamic
// icon routes, fonts, and same-origin images.
function isStaticAsset(url) {
  return (
    url.pathname.startsWith("/_next/static/") ||
    url.pathname.startsWith("/icon") ||
    url.pathname.startsWith("/apple-icon") ||
    url.pathname.startsWith("/pwa-icon") ||
    url.pathname.startsWith("/pwa-screenshot") ||
    /\\.(?:js|css|woff2?|png|jpg|jpeg|svg|webp|avif|ico)$/.test(url.pathname)
  );
}

self.addEventListener("fetch", (event) => {
  const { request } = event;

  // Only ever touch GET; let POST (contact server action), etc. hit the network.
  if (request.method !== "GET") return;

  const url = new URL(request.url);

  // Leave cross-origin (analytics, fonts CDNs we don't control) alone.
  if (url.origin !== self.location.origin) return;

  // Navigations → network-first with an offline fallback.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          // Cache a copy of the freshly fetched page for next-time offline.
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(async () => {
          const cache = await caches.open(CACHE);
          return (await cache.match(request)) || (await cache.match("/offline")) || Response.error();
        }),
    );
    return;
  }

  // Static assets → stale-while-revalidate.
  if (isStaticAsset(url)) {
    event.respondWith(
      caches.open(CACHE).then(async (cache) => {
        const cached = await cache.match(request);
        const network = fetch(request)
          .then((response) => {
            if (response && response.status === 200) cache.put(request, response.clone());
            return response;
          })
          .catch(() => cached);
        return cached || network;
      }),
    );
  }
  // Anything else: default browser handling (no respondWith).
});
`;

export function GET(): Response {
  return new Response(worker, {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // Best-effort immediate update pickup; even if a CDN layer overrides
      // this, the browser's default ≤24 h SW update check still applies.
      "Cache-Control": "no-cache",
    },
  });
}
