import type { AppCapability } from "@/types/app";

// SINGLE SOURCE OF TRUTH for human-readable capability labels — the task axis.
// Mirrors CATEGORY_LABEL exactly: `Record<AppCapability, string>` makes a missing
// label a compile error, so adding a leaf to APP_CAPABILITIES forces a label here
// (and nowhere else). No "use client" — server + client both import it. Ordered
// by family to match the APP_CAPABILITIES tuple in types/app.ts.
export const CAPABILITY_LABEL: Record<AppCapability, string> = {
  // coding
  "code-generation": "Code generation",
  "agentic-coding": "Autonomous coding agent",
  "code-review": "Code review",
  "ide-integration": "IDE integration",
  "terminal-cli-agent": "Terminal / CLI agent",
  "code-execution": "Sandboxed code execution",
  "code-documentation": "Code documentation",
  "test-generation": "Test generation",
  // agents & automation
  "agent-framework": "Agent framework",
  "agent-orchestration": "Multi-agent orchestration",
  "tool-calling": "Tool / function calling",
  "mcp-server": "MCP server",
  "mcp-gateway": "MCP gateway / registry",
  "workflow-orchestration": "Workflow orchestration",
  "automation-trigger": "Trigger-action automation",
  "browser-automation": "Browser automation",
  "web-scraping": "Web scraping",
  "voice-agent": "Voice agent",
  // model serving, training & compute
  "model-inference": "Model inference / serving",
  "llm-gateway": "LLM gateway / routing",
  "multi-model-access": "Multi-model access",
  "model-fine-tuning": "Fine-tuning / training",
  "gpu-compute": "GPU compute",
  // eval, observability & AI safety
  "eval-suite": "LLM evaluation",
  "llm-observability": "LLM observability",
  "prompt-management": "Prompt management",
  "red-teaming": "Red-teaming",
  guardrails: "Guardrails",
  "ai-security-scanning": "AI security scanning",
  "content-moderation": "Content moderation",
  // retrieval, RAG & memory
  "vector-search": "Vector search",
  embeddings: "Embeddings",
  "rag-pipeline": "RAG pipeline",
  "document-qa": "Chat with documents",
  "unified-search": "Unified search",
  "agent-memory": "Agent memory",
  "knowledge-graph": "Knowledge graph",
  "cited-answers": "Cited answers",
  recommendation: "Recommendation engine",
  // data pipeline, extraction & app building
  "ocr-extraction": "OCR / scanned-document extraction",
  "document-parsing": "Document parsing (structured)",
  "data-labeling": "Data labeling",
  "etl-pipeline": "ETL / data pipeline",
  "app-deployment": "App / agent deployment",
  "app-builder": "AI app builder",
  "text-to-sql": "Text-to-SQL",
  "spreadsheet-automation": "Spreadsheet automation",
  // speech & voice
  "speech-to-text": "Transcription (STT)",
  "text-to-speech": "Speech synthesis (TTS)",
  "voice-cloning": "Voice cloning",
  "speaker-diarization": "Speaker diarization",
  dubbing: "Dubbing",
  "speech-translation": "Speech translation",
  dictation: "Dictation",
  "subtitle-generation": "Subtitle generation",
  // audio & music
  "music-generation": "Music generation",
  "stem-separation": "Stem separation",
  "audio-cleanup": "Audio cleanup",
  "audio-mastering": "Audio mastering",
  "audio-editing": "Audio editing",
  "sound-effects": "Sound effects",
  // image generation & vision
  "text-to-image": "Text-to-image",
  "image-editing": "Image editing",
  "image-upscaling": "Image upscaling",
  "background-removal": "Background removal",
  "logo-generation": "Logo generation",
  "avatar-generation": "Avatar generation",
  "object-detection": "Object detection",
  "image-classification": "Image classification",
  "video-understanding": "Video understanding",
  "defect-detection": "Defect detection",
  // video, 3D & design
  "text-to-video": "Text-to-video",
  "image-to-video": "Image-to-video",
  "video-editing": "Video editing",
  "lip-sync": "Lip-sync",
  "text-to-3d": "Text-to-3D",
  "image-to-3d": "Image-to-3D",
  "ui-design": "UI design / design-to-code",
  "graphic-design": "Graphic design",
  "presentation-generation": "Presentation generation",
  // writing, research & knowledge
  "long-form-writing": "Long-form writing",
  "text-editing": "Editing / grammar",
  summarization: "Summarization",
  "web-research-agent": "Web research agent",
  "literature-review": "Literature review",
  "literature-search": "Literature search",
  "schema-extraction": "Structured extraction",
  "note-taking": "Note-taking / PKM",
  translation: "Translation",
  "report-generation": "Report generation",
  "text-classification": "Text classification",
  // productivity, meetings & comms
  "meeting-notes": "Meeting notes",
  "calendar-scheduling": "Calendar scheduling",
  "email-assistant": "Email assistant",
  "task-management": "Task management",
  localization: "Localization (i18n)",
  "data-analysis": "Data analysis / BI",
  // sales, marketing, support & HR
  "lead-enrichment": "Lead enrichment",
  "outbound-prospecting": "Outbound prospecting",
  "crm-automation": "CRM automation",
  "conversation-intelligence": "Conversation intelligence",
  "ticket-deflection": "Ticket deflection",
  "knowledge-base-authoring": "Knowledge base authoring",
  "ad-creative-generation": "Ad creative generation",
  "seo-optimization": "SEO optimization",
  "resume-screening": "Resume screening",
  "candidate-sourcing": "Candidate sourcing",
  "interview-assistance": "Interview assistance",
  // vertical — healthcare
  "clinical-documentation": "Clinical documentation",
  "medical-coding": "Medical coding",
  "clinical-decision-support": "Clinical decision support",
  "medical-imaging": "Medical imaging",
  "symptom-triage": "Symptom triage",
  "healthcare-ops": "Healthcare operations",
  // vertical — legal
  "contract-drafting": "Contract drafting",
  "contract-review": "Contract review",
  "contract-lifecycle": "Contract lifecycle (CLM)",
  "legal-research": "Legal research",
  "case-management": "Case management",
  "demand-letters": "Demand letters",
  "regulatory-compliance": "Regulatory compliance",
  // vertical — finance
  bookkeeping: "Bookkeeping",
  "financial-close": "Financial close",
  "expense-management": "Expense management",
  "tax-preparation": "Tax preparation",
  "financial-modeling": "Financial modeling",
  "financial-research": "Financial research",
  "financial-data-extraction": "Financial data extraction",
  "fraud-detection": "Fraud detection",
  // vertical — education
  "ai-tutoring": "AI tutoring",
  "flashcard-generation": "Flashcard generation",
  "lesson-planning": "Lesson planning",
  "homework-solving": "Homework solving",
  "language-practice": "Language practice",
  "study-material-conversion": "Study material conversion",
  // vertical — companion
  "companion-chat": "Companion chat",
  "ambient-life-capture": "Ambient life capture",
  "roleplay-characters": "Roleplay characters",
  // vertical — real estate
  "property-valuation": "Property valuation",
  "property-data-api": "Property data API",
  "virtual-staging": "Virtual staging",
  // frontier — robotics & embodied
  "robot-foundation-model": "Robot foundation model",
  "vision-language-action": "Vision-language-action",
  "dexterous-manipulation": "Dexterous manipulation",
  "bipedal-locomotion": "Bipedal locomotion",
  "imitation-learning": "Imitation learning",
  "sim-to-real": "Sim-to-real transfer",
  "world-model": "World model",
  "physics-simulation": "Physics simulation",
  "autonomous-navigation": "Autonomous navigation",
  // frontier — bio & molecular
  "protein-design": "Protein design",
  "protein-structure-prediction": "Protein structure prediction",
  "antibody-design": "Antibody design",
  "molecular-design": "Molecular design",
  "drug-target-discovery": "Drug target discovery",
  // frontier — autonomous science
  "materials-discovery": "Materials discovery",
  "autonomous-research": "Autonomous research",
};
